[default]

[default.extend-words]
deine = "deine"
ein = "ein"
Vas = "Vas"
vas = "vas"
momento = "momento"
Approche = "Approche"
presentas = "presentas"
Avance = "Avance"
dran = "dran"
Foto = "Foto"
foto = "foto"
Greif = "Greif"
als = "als"
mouvement = "mouvement"
termine = "termine"
producto = "producto"
infiniment = "infiniment"
somme = "somme"
quitt = "quitt"
Brillant = "Brillant"
attendent = "attendent"
Termine = "Termine"
posible = "posible"
egal = "egal"
mesure = "mesure"
complet = "complet"
sur = "sur"
seconde = "seconde"
sais = "sais"
Technik = "Technik"
manges = "manges"
unter = "unter"
Produkt = "Produkt"
entends = "entends"
Eis = "Eis"
ser = "ser"
hagas = "hagas"
Absolument = "Absolument"
Absolut = "Absolut"
entreprise = "entreprise"
finde = "finde"
objets = "objets"
choses = "choses"
hace = "hace"
futur = "futur"
trafic = "trafic"
capteurs = "capteurs"
sensores = "sensores"
mesures = "mesures"
experimentan = "experimentan"
planetas = "planetas"
mariage = "mariage"
projet = "projet"
Worte = "Worte"
decisiones = "decisiones"
apparence = "apparence"
photographier = "photographier"
langage = "langage"
regardes = "regardes"
