services:
  functiongemma:
    image: openmindagi/functiongemma-service:latest
    container_name: functiongemma_service
    ports:
      - "8200:8200"
    runtime: nvidia
    restart: unless-stopped
